title: Hungry Yellow Bees
description: A book blog for observation, commentary, and personal writings.
footer_text: Copyright 2021
header_feature_image: ../uploads/pages.jpg
header_text: Some dragons hoard gold. Others hoard books.
header_text_color: "#ffffff"
bannerheight: 20vmax
logo: /uploads/logo.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
items: []
