title: Library of Spilt Ink
description: A book blog for observation, commentary, and personal writings.
footer_text: Copyright 2021
header_feature_image: ../uploads/pages.jpg
header_text: All books are ink-stained; spill digital ink about them.
header_text_color: "#ffffff"
bannerheight: 20vmax
logo: ../uploads/bloglogo-version2.jpg
favicon: /uploads/favicon.ico
gridlayout: false
fixednavbar: false
upzoom: true
items:
  - name: About Me
    siteurl: /aboutme
